name: Compile LaTeX PDF for gh-pages

on:
  push:
    branches:
      - write-up

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v27
        with:
          nix_version: "2.18.1"

      - name: Build zip file
        run: |
          nix build --verbose --print-build-logs --timeout 3600 || \
            sed -i 's/url = "path:.\/tools";/url = "path:tools";/' flake.nix
          nix build --verbose --print-build-logs --timeout 3600

      - name: Deploy zip file
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result/
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'compile pdf:'
