name: Compile LaTeX PDF for gh-pages

on:
  push:
    branches:
      - write-up

jobs:
  compile-latex:
    runs-on: ubuntu-20.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up main.tex
        run: sed -i "s/% BUILT FROM/\\\\hfill Built from \\\\texttt{$(git rev-parse --short HEAD)}/" main.tex

      - name: Build PDF with Docker
        run: >
          mkdir -p zip_dir
          && docker build -t write-up-lintrans .
          && docker run --name wul write-up-lintrans
          && docker cp wul:/write-up-lintrans/lintrans.zip ./zip_dir/lintrans.zip
          && docker rm wul

      - name: Deploy zip file
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: zip_dir/
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'compile pdf:'
