name: Compile LaTeX PDF for gh-pages

on:
  push:
    branches:
      - write-up

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v27

      - name: Build zip file
        run: nix build

      - name: Deploy zip file
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result/
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'compile pdf:'
