name: Docstrings

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  docstrings:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e '.[dev]'

    - name: Run pydocstyle
      run: pydocstyle src/ tests/
