name: Docstrings

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - '.github/workflows/docstrings.yaml'
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  docstrings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v27

    - name: Run pydocstyle
      run: nix develop --command pydocstyle src/ tests/
