name: Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'

    - name: Set up Python 3.10
      if: steps.filter.outputs.src == 'true'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      if: steps.filter.outputs.src == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle toml

    - name: Run pydocstyle
      if: steps.filter.outputs.src == 'true'
      run: pydocstyle --match='(?!__init__).*\.py' src/ tests/
