name: Linting

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - '.github/workflows/linting.yaml'
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v27

    - name: Run flake8
      run: nix develop --command flake8 src/ tests/

    - name: Run pycodestyle
      run: nix develop --command pycodestyle src/ tests/
