name: Linting

on:
  push:
    branches:
      - main
      - dev/*

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e '.[dev]'

    - name: Run flake8
      run: flake8 src/ tests/

    - name: Run pycodestyle
      run: pycodestyle src/ tests/
