name: Linting

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - '.github/workflows/linting.yaml'
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  linting:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e '.[dev]'

    - name: Run flake8
      run: flake8 src/ tests/

    - name: Run pycodestyle
      run: pycodestyle src/ tests/
