name: Tests

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - '.github/workflows/tests.yaml'
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  pytest-linux:
    runs-on: ubuntu-latest

    env:
      DISPLAY: ':99.0'

    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v27

      - name: Run pytest
        run: nix develop --command pytest

      - name: Run doctests
        run: nix develop --command pytest --doctest-modules src/

  pytest-non-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    env:
      DISPLAY: ':99.0'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e '.[dev]'

      - name: Run pytest
        run: pytest

      - name: Run doctests
        run: pytest --doctest-modules src/
