name: Type Checks

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  type_checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e '.[dev]'

    - name: Run mypy
      run: mypy src/ tests/
