name: Type Checks

on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - '.github/workflows/type-checks.yaml'
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  type_checks:
    if: false # Disable mypy for now
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v27

    - name: Run mypy
      run: nix develop --command mypy src/ tests/
